---
apiVersion: v1
kind: Pod
metadata:
  name: message-gen
  labels:
    app: message-gen
spec:
  containers:
  - name: message-gen
    image: localhost:5000/message-gen
    imagePullPolicy: Always
    ports:
      - name: app
        containerPort: 3000
    env:
      - name: REDIS_HOST
        value: "redis-master"
      - name: REDIS_PORT
        value: "6379"
      - name: REDIS_PWD
        value: "none"
      - name: FORTUNES_SOURCE_TOPIC
        value: "fc_fortunes_in"
      - name: USERS_SOURCE_TOPIC
        value: "fc_users_in"
      - name: SENDER_SOURCE_TOPIC
        value: "fc_sender_in"
      - name: SCHEDULER_SOURCE_TOPIC
        value: "fc_scheduler_in"