apiVersion: v1
kind: Service
metadata:
  name: message-gen
  labels:
    app: message-gen
spec:
  selector:
    app: message-gen
  ports:
  -
    protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort