---
apiVersion: v1
kind: Pod
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  containers:
  - name: scheduler
    image: localhost:5000/scheduler
    imagePullPolicy: Always
    ports:
      - name: app
        containerPort: 3000
    env:
      - name: REDIS_HOST
        value: "redis-master"
      - name: REDIS_PORT
        value: "6379"
      - name: REDIS_PWD
        value: "none"
      - name: SCHEDULER_TARGET_TOPIC
        value: "fc_sender_out"
      - name: SCHEDULER_SOURCE_TOPIC
        value: "fc_scheduler_in"
