---
apiVersion: v1
kind: Pod
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  containers:
  - name: scheduler
    image: localhost:5000/scheduler
    imagePullPolicy: Always
    ports:
      - name: app
        containerPort: 3000
    env:
      - name: SENDER_API_URL
        value: "http://sender/"