---
apiVersion: v1
kind: Pod
metadata:
  name: facebook
  labels:
    app: facebook
spec:
  containers:
  - name: facebook
    image: localhost:5000/targetmockserver
    imagePullPolicy: Always
    ports:
      - name: app
        containerPort: 3000
    env:
      - name: TARGET_NAME
        value: "FACEBOOK"