---
apiVersion: v1
kind: Pod
metadata:
  name: instagram
  labels:
    app: instagram
spec:
  containers:
  - name: instagram
    image: localhost:5000/targetmockserver
    imagePullPolicy: Always
    ports:
      - name: app
        containerPort: 3000
    env:
      - name: TARGET_NAME
        value: "INSTAGRAM"