---
apiVersion: v1
kind: Pod
metadata:
  name: linkedin
  labels:
    app: linkedin
spec:
  containers:
  - name: linkedin
    image: localhost:5000/targetmockserver
    imagePullPolicy: Always
    ports:
      - name: app
        containerPort: 3000
    env:
      - name: TARGET_NAME
        value: "LINKEDIN"