---
apiVersion: v1
kind: Pod
metadata:
  name: sms
  labels:
    app: sms
spec:
  containers:
  - name: sms
    image: localhost:5000/targetmockserver
    imagePullPolicy: Always
    ports:
      - name: app
        containerPort: 3000
    env:
      - name: TARGET_NAME
        value: "SMS"