---
apiVersion: v1
kind: Pod
metadata:
  name: twitter
  labels:
    app: twitter
spec:
  containers:
  - name: twitter
    image: localhost:5000/targetmockserver
    imagePullPolicy: Always
    ports:
      - name: app
        containerPort: 3000
    env:
      - name: TARGET_NAME
        value: "TWITTER"